### ISSUE TITLE
Client ID

### ISSUE THREAD

**Issue by cyberboysumanjay** [dhaval-mehta/url-to-google-drive#4]
For self hosting this on my server. Where can I add CLIENT_ID and REDIRECT_URL ?

**Comment by dhaval-mehta** [comment]
You need to register on https://console.cloud.google.com/ for Google drive api. They will provide you client details including client secret

**Comment by dhaval-mehta** [comment]
i am going to create a video tutorial how to get credentials and deploy on heroku. I will put that into readme.md
