### ISSUE TITLE
Unable to upload seedr zip files

### ISSUE THREAD

**Issue by dexmorg9** [dhaval-mehta/url-to-google-drive#6]
As the tittle says,when I try uploading.zip files from seedr it fails.Here is a sample link
 https://www.seedr.cc/zip/36196404?st=e9c3ac41d25a77317a1bcee19e679a326752138a42622d160cda53dc48c45092&e=1530296429

**Comment by dhaval-mehta** [comment]
Thank you for raising issue. I am looking into it.

**Comment by gulu98** [comment]
400. That’s an error.

Error: invalid_request

**Comment by dhaval-mehta** [comment]
@gulu98 can you provide me a sample url? also can you share screenshot of error page? Thanks

**Comment by capriciousduck** [comment]
> As the tittle says,when I try uploading.zip files from seedr it fails.Here is a sample link
> https://www.seedr.cc/zip/36196404?st=e9c3ac41d25a77317a1bcee19e679a326752138a42622d160cda53dc48c45092&e=1530296429

How did you get through the google drive authentication ? I am getting an error page while authenticating. Are you running the app on heroku ? If so, what are the extra config variables needed ?

**Comment by dhaval-mehta** [comment]
will be fixed in next release.
